/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Carrusel_Compo: typeof import('./src/components/Carrusel_Compo.vue')['default']
    Header_Pagina: typeof import('./src/components/Header_Pagina.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    History: typeof import('./src/components/History.vue')['default']
    InstitucionalApp: typeof import('./src/components/InstitucionalApp.vue')['default']
    Login_Apli: typeof import('./src/components/login/Login_Apli.vue')['default']
    LoginApp: typeof import('./src/components/LoginApp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
